name: Sample GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  avni-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print a message
      run: echo "Hello, this is a sample GHA workflow!"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Verify Java version
      run: java -version
